version: '3'

services:
  app:
    build:
      context: .
    container_name: USAINUA_restAPI
    environment:
      - DB_HOST=${SSH_URL}
      - DB_PORT=3306
      - DB_NAME=${DB_USER}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - '8888:8888'