server:
  servlet:
    context-path: /USAINUA_RestAPI/
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://kino.avada-media-dev1.od.ua:3306/avada_slj_uiu
    username: avada_slj_uiu
    password: K1NxGqSHEv
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
security:
  jwt:
    secret: aGZiYmtiYWllYmNpZWFpZWJsZWNldWNlY2xhZWNhaWJlbGNhZWN3Q0VCV0VXSUM=
    access: 36000000
    refresh: 2592000000
springdoc:
  swagger-ui:
    path: /swagger-ui.html
