server:
  mvc:
    view:
      redirects:
        contextRelative: true
      prefix: /swagger-ui/
      suffix: index.html
  contextPath: /USAINUA_RestAPI
  servlet:
    context-path: /USAINUA_RestAPI
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://kino.avada-media-dev1.od.ua:3306/avada_kino
    username: avada_kino
    password: OUlIg40qOZ
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
security:
  jwt:
    secret: aGZiYmtiYWllYmNpZWFpZWJsZWNldWNlY2xhZWNhaWJlbGNhZWN3Q0VCV0VXSUM=
    access: 3600000
    refresh: 2592000000
springdoc:
  swagger-ui:
    path: /swagger-ui.html
logging:
  config: classpath:logback.xml