server:
  servlet:
    context-path: /USAINUA_RestAPI/
  port: 8888
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_LOGIN}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
security:
  jwt:
    secret: aGZiYmtiYWllYmNpZWFpZWJsZWNldWNlY2xhZWNhaWJlbGNhZWN3Q0VCV0VXSUM=
    access: 36000000
    refresh: 2592000000
springdoc:
  swagger-ui:
    path: /swagger-ui.html
logging:
  config: classpath:logback.xml