name: Deploy to Tomcat
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v3
      - name: Build the project
        run: |
          mvn package -DskipTests=true
          mvn war:war
      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: target/USAINUA_RestAPI
          remote: tomcat/webapps/USAINUA_RestAPI
          host: ${{ secrets.SSH_URL }}
          username: ${{ secrets.SSH_LOGIN }}
          password: ${{ secrets.SSH_PASSWORD }}
      - name: Copy single file to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: target/USAINUA_RestAPI.war
          remote: tomcat/webapps/USAINUA_RestAPI.war
          host: ${{ secrets.SSH_URL }}
          username: ${{ secrets.SSH_LOGIN }}
          password: ${{ secrets.SSH_PASSWORD }}
      - name: Copy configuration file to remote
        uses: garygrossgarten/github-action-scp@release
        with:
            local: path/to/application-prod.yaml
            remote: tomcat/webapps/USAINUA_RestAPI/WEB-INF/classes/application.yaml
            host: ${{ secrets.SSH_URL }}
            username: ${{ secrets.SSH_LOGIN }}
            password: ${{ secrets.SSH_PASSWORD }}