name: Deploy to Tomcat
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v3
      - name: Build the project
        run: |
          mvn package
          mvn war:war
      - name: Transfer WAR file to remote server
        uses: appleboy/scp-action@master
        with:
          host: kino.avada-media-dev1.od.ua
          username: avada_kino
          password: #Es84!4lZ0P7
          source: target/USAINUA_Admin.war
          target: /tomcat/webapps/