name: Deploy to Tomcat
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v3
      - name: Build the project
        run: |
          mvn package -DskipTests=true
          mvn war:war
      - name: Replace environment variables in application.yaml
        uses: joshwget/replace-env-vars-action@v1
        with:
          files: 'application.yaml'
          prefix: '${'
          suffix: '}'
          DB_URL: 'some_link'
          DB_LOGIN: 'some_login'
          DB_PASSWORD: 'some_password'
      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: target/USAINUA_RestAPI
          remote: tomcat/webapps/USAINUA_RestAPI
          host: ${{ secrets.SSH_URL }}
          username: ${{ secrets.SSH_LOGIN }}
          password: ${{ secrets.SSH_PASSWORD }}
      - name: Copy single file to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: target/USAINUA_RestAPI.war
          remote: tomcat/webapps/USAINUA_RestAPI.war
          host: ${{ secrets.SSH_URL }}
          username: ${{ secrets.SSH_LOGIN }}
          password: ${{ secrets.SSH_PASSWORD }}
