name: Deploy to Tomcat
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v3
      - name: Build the project
        run: |
          mvn war:war
      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: target/USAINUA_RestAPI
          remote: tomcat/webapps/USAINUA_RestAPI
          host: kino.avada-media-dev1.od.ua
          username: avada_kino
          password: "#Es84!4lZ0P7"
      - name: Copy single file to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: target/USAINUA_RestAPI.war
          remote: tomcat/webapps/USAINUA_RestAPI.war
          host: kino.avada-media-dev1.od.ua
          username: avada_kino
          password: "#Es84!4lZ0P7"