name: Deploy to Tomcat
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build the project
        run: |
          mvn package -DskipTests=true
          mvn war:war
      - name: Update application.yaml
        run: |
          sed -i -e 's|${DB_URL}|${{ secrets.DB_URL }}|g' target/USAINUA_RestAPI/WEB-INF/classes/application.yaml
          sed -i -e 's|${DB_LOGIN}|${{ secrets.DB_LOGIN }}|g' target/USAINUA_RestAPI/WEB-INF/classes/application.yaml
          sed -i -e 's|${DB_PASSWORD}|${{ secrets.DB_PASSWORD }}|g' target/USAINUA_RestAPI/WEB-INF/classes/application.yaml
      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: target/USAINUA_RestAPI
          remote: tomcat/webapps/USAINUA_RestAPI
          host: ${{ secrets.SSH_URL }}
          username: ${{ secrets.SSH_LOGIN }}
          password: ${{ secrets.SSH_PASSWORD }}
      - name: Copy single file to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: target/USAINUA_RestAPI.war
          remote: tomcat/webapps/USAINUA_RestAPI.war
          host: ${{ secrets.SSH_URL }}
          username: ${{ secrets.SSH_LOGIN }}
          password: ${{ secrets.SSH_PASSWORD }}
