name: Deploy to Tomcat
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build the project
        run: |
          mvn package
          mvn war:war
      - name: Deploy to Tomcat
        run: |
          curl -T target/USAINUA_RestAPI.war -u tomcat:OUlIg40qOZ "http://kino.avada-media-dev1.od.ua/manager/html/deploy?path=/USAINUA_RestAPI&update=true"